unit uTestOperacionSuma;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, uOperacionSuma;

type
  // Test methods for class TOperacionSuma

  TestTOperacionSuma = class(TTestCase)
  strict private
    FOperacionSuma: TOperacionSuma;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestCalcular2mas2;
    procedure TestCalcular5mas3;
    procedure TestCalcular9mas1;
  end;

implementation

procedure TestTOperacionSuma.SetUp;
begin
  FOperacionSuma := TOperacionSuma.Create;
end;

procedure TestTOperacionSuma.TearDown;
begin
  FOperacionSuma.Free;
  FOperacionSuma := nil;
end;

procedure TestTOperacionSuma.TestCalcular2mas2;
var
  ReturnValue: Integer;
begin
  FOperacionSuma.Numero1:= 2;
  FOperacionSuma.Numero2:= 2;
  ReturnValue := FOperacionSuma.Calcular;
  CheckEquals(ReturnValue, 4);
end;

procedure TestTOperacionSuma.TestCalcular5mas3;
var
  ReturnValue: Integer;
begin
  FOperacionSuma.Numero1:= 6;
  FOperacionSuma.Numero2:= 3;
  ReturnValue := FOperacionSuma.Calcular;
  CheckEquals(ReturnValue, 9);
end;

procedure TestTOperacionSuma.TestCalcular8mas1;
var
  ReturnValue: Integer;
begin
  FOperacionSuma.Numero1:= 8;
  FOperacionSuma.Numero2:= 1;
  ReturnValue := FOperacionSuma.Calcular;
  CheckEquals(ReturnValue, 9);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTOperacionSuma.Suite);
end.

